version: '3.8'
services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
      # Choose the build stage: 'prod' or 'dev'
      target: dev
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "9229:9229" # 9229 is the default node debug port
      - "${PORT}:3000"
    command: sh -c "npm run db:migrate && npm run seed && npm run start:debug"
    volumes:
      - ./be/src:/app/src

  db:
    image: postgres:alpine
    restart: always
    build:
      context: ./be
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
      # Choose the build stage: 'prod' or 'dev'
      target: dev
    ports:
      - "8000:8000"
    environment:
      - VITE_BACKEND_URL=http://backend:3000

volumes:
  db:
    driver: local
